c_compiler:
  - vs2019     # [win and x86_64]
  - vs2022     # [win and arm64]
cxx_compiler:
  - vs2019     # [win and x86_64]
  - vs2022     # [win and arm64]
fmt:
  - 10
hdf5:
  - 1.14.3
libgdal:
  - 3.8
python:
  - 3.10
