version: '{branch}-{build}'

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          LUE_MSVC_GENERATOR: Visual Studio 15 2017
          LUE_MSVC_GENERATOR_SHORT: VS2017

configuration:
    - Debug

platform:
    - x64

init:
    - cmd: |
        echo "init..."

install:
    - cmd: |
        git submodule update --init --recursive
        python --version
        echo %PATH%
        pip install --user conan
        conan user
        conan --version
        conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan
        conan install .

before_build:
    - cmd: |
        echo "before_build..."
        dir
        mkdir build
        cd build
        cmake --version
        cmake -G"%LUE_MSVC_GENERATOR%" -A%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..

build_script:
    - cmd: |
        echo "build_script..."
        dir
        cmake --config %CONFIGURATION% --target all

test_script:
    - cmd: |
        echo "test_script..."
        CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test
