version: '{branch}-{build}'

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          LUE_MSVC_GENERATOR: Visual Studio 15 2017
          LUE_MSVC_GENERATOR_SHORT: VS2017

configuration:
    - Debug

platform:
    - x64

init:
    - cmd: |
        echo "init..."

install:
    - cmd: |
        echo "install..."
        git submodule update --init --recursive
        python --version
        echo %PATH%
        pip install conan
        conan user
        conan --version

before_build:
    - cmd: |
        echo "before_build..."
        cmake --version
        cmake -G"%LUE_MSVC_GENERATOR%" -A%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION% .

build_script:
    - cmd: |
        echo "build_script..."
        cmake --config %CONFIGURATION% --target all

test_script:
    - cmd: |
        echo "test_script..."
        CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test
