---
exclude_paths:
    - "document/**"
    - "environment/**"
engines:
    - markdownlint:
        # Keep these settings in sync with .mdl_style.rb
        - MD004: false
        - MD005: false
        - MD007:
            - indent: 4
        - MD012: false
        - MD013:
            - line_length: 110
        - MD024: false
        - MD030: false
        - MD034: false
        - MD041: false
        - MD046: false
