# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  # Skip the files that must be kept as they are
  (?x)^(
    environment/cmake/.*\.patch|
    environment/cmake/UseLATEX\.cmake|
    environment/cmake/conan-.*\.cmake|
    # environment/conda/meta\.yaml|
    source/view/imgui/include/lue/imgui/font/.*
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  # - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.0
  hooks:
  - id: mypy
    # args: [--verbose]
    language: system  # Use interpreter in environment
    exclude: |
      (?x)^(
        source/data_model/python/test/.*|
        document/luepy/ext/.*|
        source/framework/case_study/.*|
        source/framework/python/test/.*|
        source/qa/python/qa/.*|
        source/qa/script/.*|
      )$
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    files: |
      (?x)^(
        .*\.py|
        .*\.py.in|
      )$
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    args: [--style=file, -i]
  - id: clang-tidy
    args: [--quiet]
    exclude: |
      (?x)^(
        source/data_model/cxx/.*|
        source/data_model/hl/.*|
        source/data_model/python/.*|
        source/data_model/test/.*|
        source/data_model/translate/.*|
        source/data_model/utility/.*|
        source/data_model/validate/.*|
        source/framework/.*|
        source/python/.*|
        source/qa/.*|
        source/view/.*|
      )$
# - repo: https://github.com/markdownlint/markdownlint
#   rev: v0.13.0
#   hooks:
#   - id: markdownlint
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.3.0
#   hooks:
#   - id: codespell
# - repo: https://github.com/crate-ci/typos
#   rev: v1.23.6
#   hooks:
#   - id: typos
# - repo: https://github.com/amperser/proselint
#   rev: 0.14.0
#   hooks:
#   - id: proselint
