language: cpp

sudo: false

# os:
#     - linux


# env:
#     - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
#     - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"


matrix:
    include:
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - libhdf5-dev
          env:
              - TRAVIS_C_COMPILER=gcc-4.9
              - TRAVIS_CXX_COMPILER=g++-4.9
              - TRAVIS_BUILD_TYPE=Debug
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
              # - TRAVIS_BUILD_TYPE=Release
              # - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"



# compiler:
#     - gcc
# 
# 
# addons:
#     apt:
#         sources:
#             - boost-latest
#             - llvm-toolchain-precise-3.5
#             - ubuntu-toolchain-r-test
#         packages:
#             - clang-3.5
#             - g++-4.9
#             - g++-5
#             - libboost1.55-all-dev



# Install/update dependencies required by the installation of the
# requirements of the project.
# Travis-specific stuff.
before_install:
    # Install a recent version of CMake.
    - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - tar zxf cmake-3.2.3-Linux-x86_64.tar.gz
    - export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH

# - if [ "$CC" = "clang" ]; then export CC="clang-3.5" CXX="clang++-3.5"; fi
# - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CXX="g++-4.9"; fi


# Install dependencies required by the project, similar to what a user would
# have to do.
# install:


# Commands which need to be executed before building the project.
# Travis-specific stuff.
# before_script:


# Build the project, similar to what a user would have to do.
script:
    - mkdir build
    - cd build
    - cmake
        -DCMAKE_C_COMPILER=$TRAVIS_C_COMPILER
        -DCMAKE_CXX_COMPILER=$TRAVIS_CXX_COMPILER
        -G"${TRAVIS_CMAKE_GENERATOR}"
        -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE}
        ..
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all
    - ctest -C ${TRAVIS_BUILD_TYPE}
