language: cpp

sudo: false

matrix:
    include:

#         # C library
#         # Debug builds
#         # gcc-4.9
#         - compiler: gcc
#           addons:
#               apt:
#                   sources:
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - g++-4.9
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_C_COMPILER=gcc-4.9
#               - TRAVIS_CXX_COMPILER=g++-4.9
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$TRAVIS_C_COMPILER"
# 
#         # clang-3.5
#         - compiler: clang
#           addons:
#               apt:
#                   sources:
#                       - llvm-toolchain-precise-3.5
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - clang-3.5
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-3.5"
# 
#         # Release builds
#         # gcc-4.9
#         - compiler: gcc
#           addons:
#               apt:
#                   sources:
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - g++-4.9
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-4.9"
# 
#         # clang-3.5
#         - compiler: clang
#           addons:
#               apt:
#                   sources:
#                       - llvm-toolchain-precise-3.5
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - clang-3.5
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-3.5"
# 
#         # C++ library
#         # Debug builds
#         # gcc-4.9
#         - compiler: gcc
#           addons:
#               apt:
#                   sources:
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - g++-4.9
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 -DLUE_BUILD_CXX_API:BOOL=TRUE"
# 
#         # clang-3.5
#         - compiler: clang
#           addons:
#               apt:
#                   sources:
#                       - llvm-toolchain-precise-3.5
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - clang-3.5
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-3.5 -DCMAKE_CXX_COMPILER=clang++-3.5 -DLUE_BUILD_CXX_API:BOOL=TRUE"
# 
#         # Release builds
#         # gcc-4.9
#         - compiler: gcc
#           addons:
#               apt:
#                   sources:
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - g++-4.9
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 -DLUE_BUILD_CXX_API:BOOL=TRUE"
# 
#         # clang-3.5
#         - compiler: clang
#           addons:
#               apt:
#                   sources:
#                       - llvm-toolchain-precise-3.5
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - clang-3.5
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-3.5 -DCMAKE_CXX_COMPILER=clang++-3.5 -DLUE_BUILD_CXX_API:BOOL=TRUE"

        # Python library
        # Debug builds
        # gcc-4.9
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - libhdf5-serial-dev
          env:
              - TRAVIS_C_COMPILER=gcc-4.9 TRAVIS_CXX_COMPILER=g++-4.9 TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$TRAVIS_C_COMPILER -DCMAKE_CXX_COMPILER=$TRAVIS_CXX_COMPILER -DLUE_BUILD_PYTHON_API:BOOL=TRUE"

#         # clang-3.5
#         - compiler: clang
#           addons:
#               apt:
#                   sources:
#                       - llvm-toolchain-precise-3.5
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - clang-3.5
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-3.5 -DCMAKE_CXX_COMPILER=clang++-3.5 -LUE_BUILD_PYTHON_API:BOOL=TRUE"
# 
#         # Release builds
#         # gcc-4.9
#         - compiler: gcc
#           addons:
#               apt:
#                   sources:
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - g++-4.9
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 -LUE_BUILD_PYTHON_API:BOOL=TRUE"
# 
#         # clang-3.5
#         - compiler: clang
#           addons:
#               apt:
#                   sources:
#                       - llvm-toolchain-precise-3.5
#                       - ubuntu-toolchain-r-test
#                   packages:
#                       - clang-3.5
#                       - libhdf5-serial-dev
#           env:
#               - TRAVIS_LUE_CMAKE_ARGUMENTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-3.5 -DCMAKE_CXX_COMPILER=clang++-3.5 -LUE_BUILD_PYTHON_API:BOOL=TRUE"







# with unit tests and without unit tests



#         sources:
#             - boost-latest
#             - llvm-toolchain-precise-3.5
#             - ubuntu-toolchain-r-test
#         packages:
#             - clang-3.5
#             - g++-4.9
#             - g++-5
#             - libboost1.55-all-dev


# Install/update dependencies required by the installation of the
# requirements of the project.
# Travis-specific stuff.
before_install:
    # Root of software we installed.
    - mkdir local

    # Locations for temporary files.
    - mkdir tmp tmp/source tmp/build


    # Install a recent version of CMake. ---------------------------------------
    # ~/tmp
    - cd tmp
    - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    # ~/local
    - cd ../local
    - tar zxf ../tmp/cmake-3.2.3-Linux-x86_64.tar.gz
    - export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH
    - cd ..


    # Install pybind11. Required for building the LUE Python API. --------------
    # ~/tmp/source
    - cd tmp/source
    - git clone --recursive https://github.com/geoneric/peacock.git
    # ~/tmp/build
    - cd ../build
    - mkdir peacock
    # ~/tmp/build/peacock
    - cd peacock
    - cmake --version
    - CXX=$TRAVIS_CXX_COMPILER cmake -Dpeacock_prefix=$TRAVIS_BUILD_DIR/local -Dbuild_pybind11=true -Dpybind11_version=1.8.0 $TRAVIS_BUILD_DIR/tmp/source/peacock
    - CXX=$TRAVIS_CXX_COMPILER cmake --build . --target all
    # - cmake -DCMAKE_CXX_COMPILER=$TRAVIS_CXX_COMPILER --build . --target all
    # ~
    - cd ../../..


# Install dependencies required by the project, similar to what a user would
# have to do.
# install:


# Commands which need to be executed before building the project.
# Travis-specific stuff.
# before_script:


# Build the project, similar to what a user would have to do.
script:
    - mkdir build
    - cd build
    - cmake -DPEACOCK_PREFIX:PATH=$TRAVIS_BUILD_DIR/local ${TRAVIS_LUE_CMAKE_ARGUMENTS} ..
    - cmake --build . --target all
    - if [[ ${TRAVIS_LUE_CMAKE_ARGUMENTS} == *"LUE_BUILD_TEST:BOOL=TRUE"* ]]; then cmake --build . --target test; fi
