[tool.isort]
known_lue = "lue, lue_test"
lines_after_imports = 2
sections = "FUTURE,STDLIB,THIRDPARTY,LUE,FIRSTPARTY,LOCALFOLDER"
profile = "black"

[tool.codespell]
skip = "*.cpp,*.hpp,*.tex,*_test.py,pyproject.toml"
ignore-words-list = "nD"
