name: "install hpx"
description: "Configure, build and install HPX, using settings needed by the LUE build, and clean-up afterwards"
inputs:
  cxx_compiler:
    required: true
  build_type:
    required: true
  cmake_preset:
    required: true
  hpx_version:
    required: true
  cache_key:
    required: true
runs:
  using: "composite"
  steps:
    - name: cache hpx
      id: cache-hpx
      uses: actions/cache@v3
      env:
        cache-name: cache-hpx
      with:
        path: $HPX_INSTALL_DIRECTORY
        key: ${{ inputs.cache_key }}
    - name: install hpx
      if: ${{ steps.cache-hpx.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        git clone --depth 1 --branch v${{ inputs.hpx_version }} https://github.com/STEllAR-GROUP/hpx.git $HPX_SOURCE_DIRECTORY
        cp $HPX_CMAKE_PRESET_FILE $HPX_SOURCE_DIRECTORY/CMakeUserPresets.json

        mkdir $HPX_BUILD_DIRECTORY

        cd $HPX_SOURCE_DIRECTORY
        cmake \
            --preset ${{ inputs.cmake_preset }}
            -B $HPX_BUILD_DIRECTORY \
            -G "Ninja" \
            -D CMAKE_CXX_COMPILER=${{ inputs.cxx_compiler }} \
            -D CMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            $HPX_CMAKE_FLAGS
        cd -

        cmake --build $HPX_BUILD_DIRECTORY --target all
        cmake --install $HPX_BUILD_DIRECTORY --prefix $HPX_INSTALL_DIRECTORY --strip

        rm -fr $HPX_BUILD_DIRECTORY $HPX_SOURCE_DIRECTORY
