name: "install hpx"
description: "Configure, build and install HPX, using settings needed by the LUE build, and clean-up afterwards"
inputs:
  c_compiler:
    required: true
  cxx_compiler:
    required: true
  build_type:
    required: true
  cmake_preset:
    required: true
  cmake_preset_file:
    required: true
  cmake_flags:
    required: true
  hpx_branch:
    required: true
  cache_key:
    required: true
  source_directory:
    required: true
  build_directory:
    required: true
  install_directory:
    required: true
runs:
  using: "composite"
  steps:
    - name: cache hpx
      id: cache-hpx
      uses: actions/cache@v4
      env:
        cache-name: cache-hpx
      with:
        path: ${{ inputs.install_directory }}
        key: ${{ inputs.cache_key }}
    - name: install hpx
      shell: bash -l {0}
      if: ${{ steps.cache-hpx.outputs.cache-hit != 'true' }}
      run: |
        if [ ! -d "${{ inputs.source_directory }}" ]; then
            # In case the source dir exists, the caller likely put some files in there for us to use
            cd ${{ inputs.source_directory }}
            git init
            git remote add upstream https://github.com/STEllAR-GROUP/hpx.git
            git fetch --depth=1 --tags upstream ${{ inputs.hpx_branch }}
            git checkout --force ${{ inputs.hpx_branch }}
            cd ..
        else
            git clone --depth 1 --branch ${{ inputs.hpx_branch }} https://github.com/STEllAR-GROUP/hpx.git ${{ inputs.source_directory }}
        fi

        cp ${{ inputs.cmake_preset_file }} ${{ inputs.source_directory }}/CMakeUserPresets.json

        mkdir -p ${{ inputs.build_directory }}

        cmake \
            -S ${{ inputs.source_directory }} \
            -B ${{ inputs.build_directory }} \
            --preset ${{ inputs.cmake_preset }} \
            -G "Ninja" \
            -D CMAKE_CXX_COMPILER=${{ inputs.cxx_compiler }} \
            -D CMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            -D CMAKE_POLICY_DEFAULT_CMP0167=OLD \
            ${{ inputs.cmake_flags }}
        cmake --build ${{ inputs.build_directory }} --target all
        cmake --install ${{ inputs.build_directory }} --prefix ${{ inputs.install_directory }} --strip

        rm -fr ${{ inputs.build_directory }} ${{ inputs.source_directory }}
