name: "install mdspan"
description: "Configure, build and install MDSpan, and clean-up afterwards"
inputs:
  cxx_compiler:
    required: true
  build_type:
    required: true
  mdspan_tag:
    required: true
  source_directory:
    required: true
  build_directory:
    required: true
  install_directory:
    required: true
runs:
  using: "composite"
  steps:
    - name: install mdspan
      shell: bash
      run: |
        git clone https://github.com/kokkos/mdspan.git ${{ inputs.source_directory }}

        cd ${{ inputs.source_directory }}
        git checkout ${{ inputs.mdspan_tag }}
        cd -

        mkdir ${{ inputs.build_directory }}

        cmake \
            -S ${{ inputs.source_directory }} \
            -B ${{ inputs.build_directory }} \
            -G "Ninja" \
            -D CMAKE_CXX_COMPILER=${{ inputs.cxx_compiler }} \
            -D CMAKE_BUILD_TYPE=${{ inputs.build_type }}

        cmake --build ${{ inputs.build_directory }} --target all
        cmake --install ${{ inputs.build_directory }} --prefix ${{ inputs.install_directory }} --strip

        rm -fr ${{ inputs.build_directory }} ${{ inputs.source_directory }}
