name: lue
channels:
- conda-forge
- defaults
dependencies:
# - breathe  # Generating docs
- conan  # Use this one in case the version is fine
- docopt
# - doxygen  # Generating docs
- numpy
# - pip
# - pip:
#   - conan  # Use this one in case Conda's version is out of date
# - python=3.10  # Ubuntu 22.04
# - sphinx  # Generating docs
