name: Linux CI

on:
  push:
    branches-ignore:
      - "ghxyz"
    paths:
      - ".github/actions/**"
      - ".github/workflows/linux.yml"
      - "conanfile.py"
      - "CMakePresets.json"
      - "CMakeHPXPresets.json"
      - "environment/cmake/**"
      - "environment/script/write_conan_profile.py"
      - "source/**"
      - "!source/qa/python/qa/**"

jobs:
    build:

        strategy:
            matrix:
                os: ["ubuntu-22.04"]
                python_version: ["3.9", "3.12"]
                compiler:
                    # To be recognized by Conan, name must be one of:
                    #     'Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'intel-cc', 'mcst-lcc',
                    #     'msvc', 'qcc', 'sun-cc'
                    - { name: gcc  , version:  9, cc: gcc-9   , cxx: g++-9     , package: g++-9    }
                    - { name: gcc  , version: 12, cc: gcc-12  , cxx: g++-12    , package: g++-12   }
                    - { name: clang, version: 11, cc: clang-11, cxx: clang++-11, package: clang-11 }
                    - { name: clang, version: 15, cc: clang-15, cxx: clang++-15, package: clang-15 }
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} / ${{ matrix.compiler.cxx }} / python - ${{ matrix.python_version }}

        defaults:
          run:
            shell: bash -l {0}

        env:
          lue_source_directory: $GITHUB_WORKSPACE
          lue_build_directory: $GITHUB_WORKSPACE/../build
          lue_runtime_install_directory: $GITHUB_WORKSPACE/../runtime_install
          lue_development_install_directory: $GITHUB_WORKSPACE/../development_install
          lue_consume_source_directory: $GITHUB_WORKSPACE/../lue_consume
          lue_consume_build_directory: $GITHUB_WORKSPACE/../lue_consume_build
          hpx_version: 1.9.1
          hpx_source_directory: $GITHUB_WORKSPACE/../hpx-source
          hpx_build_directory: $GITHUB_WORKSPACE/../hpx-build
          hpx_install_directory: $GITHUB_WORKSPACE/../hpx-install
          mdspan_source_directory: $GITHUB_WORKSPACE/../mdspan-source
          mdspan_build_directory: $GITHUB_WORKSPACE/../mdspan-build
          mdspan_install_directory: $GITHUB_WORKSPACE/../mdspan-install

        steps:

        - uses: actions/checkout@v4

        - uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python_version }}
            cache: "pip"
            cache-dependency-path: "**/requirements-dev.txt"

        - name: setup platform
          run: |
              sudo apt-get update
              sudo apt-get remove libunwind-14-dev
              sudo apt-get install \
                  cmake \
                  doxygen \
                  graphviz \
                  hwloc \
                  lftp \
                  libasio-dev \
                  libboost-all-dev \
                  libdocopt-dev \
                  libfmt-dev \
                  libglfw3-dev \
                  libgdal-dev \
                  libgoogle-perftools-dev \
                  libhdf5-dev \
                  libvulkan-dev \
                  ${{ matrix.compiler.package }} \
                  ninja-build \
                  nlohmann-json3-dev
              pip3 install -r environment/configuration/requirements-dev.txt

              # Expand all variables that contain variables themselves and store the values in
              # a bash script which can be used by job steps and composite actions
              echo "LUE_SOURCE_DIRECTORY=${{ env.lue_source_directory }}" >> $GITHUB_ENV
              echo "LUE_BUILD_DIRECTORY=${{ env.lue_build_directory }}" >> $GITHUB_ENV
              echo "LUE_RUNTIME_INSTALL_DIRECTORY=${{ env.lue_runtime_install_directory }}" >> $GITHUB_ENV
              echo "LUE_DEVELOPMENT_INSTALL_DIRECTORY=${{ env.lue_development_install_directory }}" >> $GITHUB_ENV
              echo "LUE_CONSUME_SOURCE_DIRECTORY=${{ env.lue_consume_source_directory }}" >> $GITHUB_ENV
              echo "LUE_CONSUME_BUILD_DIRECTORY=${{ env.lue_consume_build_directory }}" >> $GITHUB_ENV
              echo "HPX_SOURCE_DIRECTORY=${{ env.hpx_source_directory }}" >> $GITHUB_ENV
              echo "HPX_BUILD_DIRECTORY=${{ env.hpx_build_directory }}" >> $GITHUB_ENV
              echo "HPX_INSTALL_DIRECTORY=${{ env.hpx_install_directory }}" >> $GITHUB_ENV
              echo "HPX_CMAKE_PRESET_FILE=${{ env.lue_source_directory }}/CMakeHPXPresets.json" >> $GITHUB_ENV
              echo "MDSPAN_SOURCE_DIRECTORY=${{ env.mdspan_source_directory }}" >> $GITHUB_ENV
              echo "MDSPAN_BUILD_DIRECTORY=${{ env.mdspan_build_directory }}" >> $GITHUB_ENV
              echo "MDSPAN_INSTALL_DIRECTORY=${{ env.mdspan_install_directory }}" >> $GITHUB_ENV

        - name: "install hpx"
          uses: ./.github/actions/install_hpx
          with:
            cxx_compiler: ${{ matrix.compiler.cxx }}
            build_type: Release
            cmake_preset: hpx_release_linux_node_configuration
            hpx_version: ${{ env.hpx_version }}
            cache_key: ${{ matrix.os }}_${{ matrix.compiler.cxx }}_python-${{ matrix.python_version }}_hpx-${{ env.hpx_version }}

        - name: "install mdspan"
          uses: ./.github/actions/install_mdspan
          with:
            cxx_compiler: ${{ matrix.compiler.cxx }}
            build_type: Release
            mdspan_tag: a799088  # 20191010

        - name: configure
          run: |
              python3 environment/script/write_conan_profile.py ${{ matrix.compiler.name }} host_profile
              python3 environment/script/write_conan_profile.py ${{ matrix.compiler.name }} build_profile
              mkdir ${{ env.lue_build_directory }}
              CXX=${{ matrix.compiler.cxx }} LUE_CONAN_PACKAGES="imgui" \
                  conan install . \
                      --profile:host=host_profile \
                      --profile:build=build_profile \
                      --build=missing \
                      --output-folder=${{ env.lue_build_directory }}
              CMAKE_PREFIX_PATH=${{ env.lue_build_directory }} \
                  cmake --preset conan-release \
                      -B ${{ env.lue_build_directory }} \
                      -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                      -D CMAKE_POLICY_DEFAULT_CMP0144=NEW \
                      -D LUE_BUILD_DOCUMENTATION=TRUE \
                      -D LUE_BUILD_QA=TRUE \
                      -D LUE_QA_WITH_PYTHON_API=TRUE \
                      -D LUE_QA_WITH_TESTS=TRUE \
                      -D LUE_QA_TEST_NR_LOCALITIES_PER_TEST=1 \
                      -D LUE_QA_TEST_NR_THREADS_PER_LOCALITY=2 \
                      -D LUE_DATA_MODEL_WITH_PYTHON_API=TRUE \
                      -D LUE_DATA_MODEL_WITH_UTILITIES=TRUE \
                      -D LUE_FRAMEWORK_WITH_PYTHON_API=TRUE \
                      -D HPX_ROOT=${{ env.hpx_install_directory }} \
                      -D MDSPAN_ROOT=${{ env.mdspan_install_directory }}

        - name: build
          run: |
              cmake --build ${{ env.lue_build_directory }} --target all

        - name: install
          run: |
              cmake \
                  --install ${{ env.lue_build_directory }} \
                  --prefix ${{ env.lue_runtime_install_directory }} \
                  --component lue_runtime \
                  --strip
              cmake \
                  --install ${{ env.lue_build_directory }} \
                  --prefix ${{ env.lue_development_install_directory }} \
                  --component lue_development \
                  --strip

        - name: test
          run: |
              # Unit tests
              ctest --test-dir ${{ env.lue_build_directory }} --output-on-failure

              # Test of runtime targets
              ${{ env.lue_runtime_install_directory }}/bin/lue_translate --version
              ${{ env.lue_runtime_install_directory }}/bin/lue_validate --version
              ${{ env.lue_runtime_install_directory }}/bin/lue_view --version

              export PYTHONPATH="${{ env.lue_runtime_install_directory }}/lib/python${{ matrix.python_version }}:$PYTHONPATH"
              export LD_LIBRARY_PATH="${{ env.hpx_install_directory }}/lib:$LD_LIBRARY_PATH"
              ${{ env.lue_runtime_install_directory }}/bin/lue_calculate --version
              ${{ env.lue_runtime_install_directory }}/bin/lue_scalability --version
              python3 -c "import lue, lue.data_model, lue.framework, lue.pcraster, lue.qa.scalability; print(lue.__version__)"

              # Test of imported CMake targets
              git clone https://github.com/computationalgeography/lue_consume.git ${{ env.lue_consume_source_directory }}
              cmake \
                  -S ${{ env.lue_consume_source_directory }} \
                  -B ${{ env.lue_consume_build_directory }} \
                  -G "Ninja" \
                  -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                  -D CMAKE_BUILD_TYPE=Release \
                  -D CMAKE_POLICY_DEFAULT_CMP0144=NEW \
                  -D LUE_ROOT=${{ env.lue_development_install_directory }} \
                  -D HPX_ROOT=${{ env.hpx_install_directory }} \
                  -D MDSPAN_ROOT=${{ env.mdspan_install_directory }}
              cmake --build ${{ env.lue_consume_build_directory }} --target all
              ${{ env.lue_consume_build_directory }}/lue_consume_data_model
              ${{ env.lue_consume_build_directory }}/lue_consume_framework

        # - name: source package
        #   run: |
        #       cmake \
        #           --build ${{ env.lue_build_directory }} \
        #           --target package_source
        #       mkdir src
        #       cd src
        #       tar zxf ../lue-*.tar.gz
        #       mkdir bld
        #       cd lue-*
        #       ln -s ${{ env.lue_build_directory }}/CMakePresets.json CMakeUserPresets.json
        #       # TODO Source package does not yet contain the generated source files
        #       # CMAKE_PREFIX_PATH=${{ env.lue_build_directory }} \
        #       #     cmake --preset conan-release \
        #       #         -B bld \
        #       #         -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
        #       #         -D LUE_DATA_MODEL_WITH_PYTHON_API=TRUE \
        #       #         -D LUE_DATA_MODEL_WITH_UTILITIES=TRUE \
        #       #         -D LUE_BUILD_VIEW=TRUE \
        #       #         -D LUE_BUILD_QA=TRUE \
        #       #         -D LUE_QA_WITH_PYTHON_API=TRUE \
        #       #         -D LUE_FRAMEWORK_WITH_PYTHON_API=TRUE

        #       # TODO Test configuring and building the source package

        - name: documentation
          if: github.ref == 'refs/heads/master' && matrix.compiler.cxx == 'g++-12' && matrix.python_version == '3.10'
          env:
              ftp_server: ${{ secrets.FTP_SERVER }}
              ftp_port: ${{ secrets.FTP_PORT }}
              ftp_username: ${{ secrets.FTP_USERNAME }}
              ftp_password: ${{ secrets.FTP_PASSWORD }}
              remote_dir: ${{ secrets.FTP_REMOTE_DIR }}
              local_dir: "sphinx/"
          run: |
              cmake --build ${{ env.lue_build_directory }} --target cpp_doc py_doc
              cmake --build ${{ env.lue_build_directory }} --target sphinx_doc
              mkdir -p $HOME/.ssh
              echo "HostKeyAlgorithms ssh-rsa" >> $HOME/.ssh/config
              echo "PubkeyAcceptedKeyTypes ssh-rsa" >> $HOME/.ssh/config
              echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
              cd ${{ env.lue_build_directory }}/document/doc
              lftp -e "mirror --reverse --delete --transfer-all --parallel=2 $local_dir $remote_dir/doc; quit" -u $ftp_username,$ftp_password sftp://$ftp_server -p $ftp_port
