name: Linux CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: checkout submodules
          shell: bash
          run: |
              auth_header="$(git config --local \
                  --get http.https://github.com/.extraheader)"
              git submodule sync --recursive
              git -c "http.extraheader=$auth_header" -c protocol.version=2 \
                  submodule update --init --force --recursive --depth=1

        - name: install dependencies
          run: |
              sudo apt update && \
              sudo apt upgrade && \
              sudo apt install cmake libboost-all-dev ninja-build

        - name: configure
          shell: bash
          run: |
            cmake \
                -H. \
                -Bbuild \
                -GNinja \
                -DCMAKE_BUILD_TYPE=Debug

        - name: build
          shell: bash
          run: |
              cmake --build build --target all
              cmake --build build --target tests

        - name: test
          shell: bash
          run: |
              cd build
              ctest --output-on-failure
