name: Linux CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: checkout submodules
          shell: bash
          run: |
              auth_header="$(git config --local \
                  --get http.https://github.com/.extraheader)"
              git submodule sync --recursive
              git -c "http.extraheader=$auth_header" -c protocol.version=2 \
                  submodule update --init --force --recursive --depth=1

        - name: install dependencies
          run: |
              sudo apt update
              sudo apt autoremove
              sudo apt upgrade
              sudo apt install \
                  cmake libboost-all-dev libhdf5-dev ninja-build
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              export PATH="$HOME/miniconda/bin:$PATH"
              hash -r
              conda config --set always_yes yes --set changeps1 no
              conda update -q conda
              conda config --add channels conda-forge
              conda config --set show_channel_urls true
              conda info -a
              conda create -q -n test-environment python=2.7 \
                  conan docopt numpy psutil sphinx
              source activate test-environment
              conan profile new --detect default
              conan profile update settings.compiler.libcxx=libstdc++11 default
              conan remote add \
                  public-conan https://api.bintray.com/conan/bincrafters/public-conan
              mkdir build
              cd build
              conan install ..

        - name: configure
          shell: bash
          run: |
              cmake \
                  -S . \
                  -B build \
                  -G"Unix Makefiles" \
                  -DCMAKE_BUILD_TYPE=Debug \
                  -DLUE_BUILD_TEST=TRUE

        - name: build
          shell: bash
          run: |
              cmake --build build --target all

        - name: test
          shell: bash
          run: |
              cd build
              ctest --output-on-failure
