name: macOS CI

on:
  push:
    branches-ignore:
      - "ghxyz"
    paths:
      - "conanfile.py"
      - ".github/workflows/macos.yml"
      - "environment/cmake/**"
      - "environment/script/write_conan_profile.py"
      - "source/**"
      - "!source/qa/python/qa/**"

jobs:
    build:

        strategy:
            matrix:
                os: ["macos-11"]
                compiler:
                    - { name: clang, cc: clang, cxx: clang++ }
            fail-fast: true

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        defaults:
          run:
            shell: bash -l {0}

        env:
          source_directory: $GITHUB_WORKSPACE
          build_directory: $GITHUB_WORKSPACE/../build
          runtime_install_directory: $GITHUB_WORKSPACE/../runtime_install
          development_install_directory: $GITHUB_WORKSPACE/../development_install

        steps:

        - uses: actions/checkout@v3

        - name: install packages
          run: |
              brew install \
                  asio \
                  boost \
                  doxygen \
                  fmt \
                  gdal \
                  glfw \
                  graphviz \
                  gperftools \
                  hdf5 \
                  hwloc \
                  ninja \
                  nlohmann-json \
                  numpy \
                  pybind11 \
                  tree \
                  vulkan-loader

        - name: install python packages
          run: |
              pip3 install "conan>=2" docopt jinja2 matplotlib ruamel.yaml

        - name: configure
          run: |
              python3 environment/script/write_conan_profile.py ${{ matrix.compiler.name }} host_profile
              python3 environment/script/write_conan_profile.py ${{ matrix.compiler.name }} build_profile
              mkdir ${{ env.build_directory }}
              LUE_CONAN_PACKAGES="docopt.cpp imgui" conan install . \
                  --profile:host=host_profile \
                  --profile:build=build_profile \
                  --build=missing \
                  --output-folder=${{ env.build_directory }}
              CMAKE_PREFIX_PATH=${{ env.build_directory }} \
                  cmake --preset conan-release \
                      -B ${{ env.build_directory }} \
                      -D LUE_BUILD_QA=TRUE \
                      -D LUE_QA_WITH_PYTHON_API=TRUE \
                      -D LUE_QA_WITH_TESTS=TRUE \
                      -D LUE_QA_TEST_NR_LOCALITIES_PER_TEST=1 \
                      -D LUE_QA_TEST_NR_THREADS_PER_LOCALITY=2 \
                      -D LUE_DATA_MODEL_WITH_PYTHON_API=TRUE \
                      -D LUE_DATA_MODEL_WITH_UTILITIES=TRUE \
                      -D LUE_FRAMEWORK_WITH_PYTHON_API=TRUE \
                      -D LUE_BUILD_HPX=TRUE \
                      -D HPX_USE_CMAKE_CXX_STANDARD=TRUE \
                      -D HPX_WITH_MALLOC="tcmalloc" \
                      -D HPX_WITH_PKGCONFIG=FALSE \
                      -D HPX_WITH_EXAMPLES=FALSE \
                      -D HPX_WITH_TESTS=FALSE \
                      -D Python3_EXECUTABLE="/usr/local/bin/python3"

        - name: build
          run: |
              cmake --build ${{ env.build_directory }} --target all

        - name: test
          run: |
              ctest --test-dir ${{ env.build_directory }} --output-on-failure

        - name: runtime install
          run: |
              cmake \
                  --install ${{ env.build_directory }} \
                  --prefix ${{ env.runtime_install_directory }} \
                  --component runtime \
                  --strip
              cmake \
                  --install ${{ env.build_directory }} \
                  --prefix ${{ env.runtime_install_directory }} \
                  --component lue_runtime \
                  --strip

              ${{ env.runtime_install_directory }}/bin/lue_translate --version
              ${{ env.runtime_install_directory }}/bin/lue_validate --version
              ${{ env.runtime_install_directory }}/bin/lue_view --version

              export PYTHONPATH="$(echo ${{ env.runtime_install_directory }}/lib/python3.*):$PYTHONPATH"
              python3 ${{ env.runtime_install_directory }}/bin/lue_calculate --version
              python3 ${{ env.runtime_install_directory }}/bin/lue_scalability --version
              python3 -c "import lue, lue.data_model, lue.framework, lue.pcraster, lue.qa.scalability; print(lue.__version__)"
