name: macOS Conda package

on:
  push:
    branches-ignore:
      - "ghxyz"
    paths:
      - "conanfile.py"
      - ".github/workflows/macos-conda.yml"
      - "source/**"
      - "!source/qa/python/qa/**"
      - "environment/cmake/**"
      - "environment/conda/build.sh"
      - "environment/conda/conda_build_config.yaml"
      - "environment/conda/meta.yaml"
      - "environment/conda/run_test.py"
      - "environment/script/write_conan_profile.py"

jobs:
    build:
        name: ${{ matrix.os }} / ${{ matrix.target-platform }} / conda
        runs-on: ${{ matrix.os }}
        timeout-minutes: 120
        defaults:
            run:
                shell: bash -l {0}
        strategy:
            matrix:
                include:
                - os: "macos-latest"
                  target-platform: osx-64
            fail-fast: true
        steps:
        - uses: actions/checkout@v4
        - uses: conda-incubator/setup-miniconda@v3
          with:
              miniforge-version: latest
              auto-update-conda: false
        - run: |
              mamba install boa
              conda mambabuild environment/conda --override-channels --channel conda-forge
