name: macOS Conda package

on:
  push:
    branches-ignore:
      - "ghxyz"
    paths:
      - "conanfile.py"
      - ".github/workflows/macos-conda.yml"
      - "source/**"
      - "!source/qa/python/qa/**"
      - "environment/cmake/**"
      - "environment/conda/build.sh"
      - "environment/conda/conda_build_config.yaml"
      - "environment/conda/meta.yaml"
      - "environment/conda/run_test.py"
      - "environment/script/write_conan_profile.py"

jobs:
    build:

        strategy:
            matrix:
                os: ["macos-latest"]
                python-version: ["3.9"]
            fail-fast: true

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} / python - ${{ matrix.python-version }}

        timeout-minutes: 120

        steps:

        - name: Checkout LUE
          uses: actions/checkout@v4

        - uses: conda-incubator/setup-miniconda@v2
          with:
              miniconda-version: "latest"
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge

        - name: Build
          shell: bash -l {0}
          run: |
              conda install boa
              conda mambabuild environment/conda --override-channels --channel conda-forge

        - uses: Dylan700/sftp-upload-action@latest
          # TODO if: github.ref == 'refs/heads/master'
          with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              port: ${{ secrets.FTP_PORT }}
              uploads: |
                  /Users/runner/miniconda3/envs/test/conda-bld/osx-64/ => ${{ secrets.FTP_REMOTE_DIR }}/download/conda/osx-64/
