name: macOS Conda package

on: [push]

jobs:
    build:

        strategy:
            matrix:
                os: ["macos-latest"]
                python-version: [3.8]

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        steps:

        - name: checkout lue
          uses: actions/checkout@v2

        - name: configure system
          run: |
              brew update
              brew upgrade

        - uses: goanpeca/setup-miniconda@v1
          with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge
