name: macOS Conda package

on: [push]

jobs:
    build:

        strategy:
            matrix:
                os: ["macos-11"]
                python-version: [3.9]

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        steps:

        - name: checkout lue
          uses: actions/checkout@v2

        - name: configure system
          run: |
              # brew update
              # brew upgrade

        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge
