name: macOS CI

on:
  push:
    branches-ignore:
      - "ghxyz"
    paths:
      - "conanfile.py"
      - ".github/actions/**"
      - ".github/workflows/macos.yml"
      - "environment/cmake/**"
      - "environment/script/write_conan_profile.py"
      - "source/**"
      - "!source/qa/python/qa/**"

jobs:
    build:

        strategy:
            matrix:
                os: ["macos-12"]
                compiler:
                    - { name: clang, cc: clang, cxx: clang++ }
                python_version: ["3.11"]
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} / ${{ matrix.compiler.cxx }}

        defaults:
          run:
            shell: bash -l {0}

        env:
          lue_source_directory: $GITHUB_WORKSPACE
          lue_build_directory: $GITHUB_WORKSPACE/../build
          lue_runtime_install_directory: $GITHUB_WORKSPACE/../runtime_install
          lue_development_install_directory: $GITHUB_WORKSPACE/../development_install
          lue_consume_source_directory: $GITHUB_WORKSPACE/../lue_consume
          lue_consume_build_directory: $GITHUB_WORKSPACE/../lue_consume_build
          hpx_version: 1.9.1
          hpx_source_directory: $GITHUB_WORKSPACE/../hpx-1.9.1
          hpx_build_directory: $GITHUB_WORKSPACE/../hpx-build
          hpx_install_directory: $GITHUB_WORKSPACE/../hpx-install
          mdspan_source_directory: $GITHUB_WORKSPACE/../mdspan-source
          mdspan_build_directory: $GITHUB_WORKSPACE/../mdspan-build
          mdspan_install_directory: $GITHUB_WORKSPACE/../mdspan-install

        steps:

        - uses: actions/checkout@v4

        - name: setup platform
          run: |
              brew install \
                  asio \
                  boost \
                  doxygen \
                  fmt \
                  gdal \
                  glfw \
                  graphviz \
                  gperftools \
                  hdf5 \
                  hwloc \
                  ninja \
                  nlohmann-json \
                  numpy \
                  pybind11 \
                  tree \
                  vulkan-loader
              pip3 install conan docopt jinja2 matplotlib ruamel.yaml

              # Expand all variables that contain variables themselves and store the values in
              # a bash script which can be used by job steps and composite actions
              echo "LUE_SOURCE_DIRECTORY=${{ env.lue_source_directory }}" >> $GITHUB_ENV
              echo "LUE_BUILD_DIRECTORY=${{ env.lue_build_directory }}" >> $GITHUB_ENV
              echo "LUE_RUNTIME_INSTALL_DIRECTORY=${{ env.lue_runtime_install_directory }}" >> $GITHUB_ENV
              echo "LUE_DEVELOPMENT_INSTALL_DIRECTORY=${{ env.lue_development_install_directory }}" >> $GITHUB_ENV
              echo "LUE_CONSUME_SOURCE_DIRECTORY=${{ env.lue_consume_source_directory }}" >> $GITHUB_ENV
              echo "LUE_CONSUME_BUILD_DIRECTORY=${{ env.lue_consume_build_directory }}" >> $GITHUB_ENV
              echo "HPX_SOURCE_DIRECTORY=${{ env.hpx_source_directory }}" >> $GITHUB_ENV
              echo "HPX_BUILD_DIRECTORY=${{ env.hpx_build_directory }}" >> $GITHUB_ENV
              echo "HPX_INSTALL_DIRECTORY=${{ env.hpx_install_directory }}" >> $GITHUB_ENV
              echo "HPX_CMAKE_PRESET_FILE=${{ env.lue_source_directory }}/CMakeHPXPresets.json" >> $GITHUB_ENV
              echo "MDSPAN_SOURCE_DIRECTORY=${{ env.mdspan_source_directory }}" >> $GITHUB_ENV
              echo "MDSPAN_BUILD_DIRECTORY=${{ env.mdspan_build_directory }}" >> $GITHUB_ENV
              echo "MDSPAN_INSTALL_DIRECTORY=${{ env.mdspan_install_directory }}" >> $GITHUB_ENV

                "HPX_WITH_MALLOC": "tcmalloc",
                "HPX_WITH_GOOGLE_PERFTOOLS": "TRUE",

        - name: "install hpx"
          uses: ./.github/actions/install_hpx
          with:
            cxx_compiler: ${{ matrix.compiler.name }}
            build_type: Release
            hpx_version: ${{ env.hpx_version }}
            cache_key: ${{ matrix.os }}_${{ matrix.compiler.cxx }}_python-${{ matrix.python_version }}_hpx-${{ env.hpx_version }}

        - name: "install mdspan"
          uses: ./.github/actions/install_mdspan
          with:
            cxx_compiler: ${{ matrix.compiler.name }}
            build_type: Release
            cmake_preset: hpx_release_macos_node_configuration
            mdspan_tag: a799088  # 20191010

        - name: configure
          run: |
              python3 environment/script/write_conan_profile.py ${{ matrix.compiler.name }} host_profile
              python3 environment/script/write_conan_profile.py ${{ matrix.compiler.name }} build_profile
              mkdir ${{ env.lue_build_directory }}
              LUE_CONAN_PACKAGES="docopt.cpp imgui" \
                  conan install . \
                    --profile:host=host_profile \
                    --profile:build=build_profile \
                    --build=missing \
                    --output-folder=${{ env.lue_build_directory }}
              CMAKE_PREFIX_PATH=${{ env.lue_build_directory }} \
                  cmake --preset conan-release \
                      -B ${{ env.lue_build_directory }} \
                      -D LUE_BUILD_QA=TRUE \
                      -D LUE_QA_WITH_PYTHON_API=TRUE \
                      -D LUE_QA_WITH_TESTS=TRUE \
                      -D LUE_QA_TEST_NR_LOCALITIES_PER_TEST=1 \
                      -D LUE_QA_TEST_NR_THREADS_PER_LOCALITY=2 \
                      -D LUE_DATA_MODEL_WITH_PYTHON_API=TRUE \
                      -D LUE_DATA_MODEL_WITH_UTILITIES=TRUE \
                      -D LUE_FRAMEWORK_WITH_PYTHON_API=TRUE \
                      -D HPX_ROOT=${{ env.hpx_install_directory }} \
                      -D MDSPAN_ROOT=${{ env.mdspan_install_directory }}
                      -D Python3_EXECUTABLE="/usr/local/bin/python3"

        - name: build
          run: |
              cmake --build ${{ env.lue_build_directory }} --target all

        - name: install
          run: |
              cmake \
                  --install ${{ env.lue_build_directory }} \
                  --prefix ${{ env.lue_runtime_install_directory }} \
                  --component lue_runtime \
                  --strip
              cmake \
                  --install ${{ env.lue_build_directory }} \
                  --prefix ${{ env.lue_development_install_directory }} \
                  --component lue_development \
                  --strip

        - name: test
          run: |
              # Unit tests
              ctest --test-dir ${{ env.lue_build_directory }} --output-on-failure

              # Test of runtime targets
              ${{ env.lue_runtime_install_directory }}/bin/lue_translate --version
              ${{ env.lue_runtime_install_directory }}/bin/lue_validate --version
              ${{ env.lue_runtime_install_directory }}/bin/lue_view --version

              export PYTHONPATH="${{ env.lue_runtime_install_directory }}/lib/python${{ matrix.python_version}}:$PYTHONPATH"
              python3 ${{ env.lue_runtime_install_directory }}/bin/lue_calculate --version
              python3 ${{ env.lue_runtime_install_directory }}/bin/lue_scalability --version
              python3 -c "import lue, lue.data_model, lue.framework, lue.pcraster, lue.qa.scalability; print(lue.__version__)"

              # Test of imported CMake targets
              git clone https://github.com/computationalgeography/lue_consume.git ${{ env.lue_consume_source_directory }}
              cmake \
                  -S ${{ env.lue_consume_source_directory }} \
                  -B ${{ env.lue_consume_build_directory }} \
                  -G "Ninja" \
                  -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                  -D CMAKE_BUILD_TYPE=Release \
                  -D CMAKE_POLICY_DEFAULT_CMP0144=NEW \
                  -D LUE_ROOT=${{ env.lue_development_install_directory }} \
                  -D HPX_ROOT=${{ env.hpx_install_directory }} \
                  -D MDSPAN_ROOT=${{ env.mdspan_install_directory }}
              cmake --build ${{ env.lue_consume_build_directory }} --target all
              ${{ env.lue_consume_build_directory }}/lue_consume_data_model
              ${{ env.lue_consume_build_directory }}/lue_consume_framework
