name: Code quality assurance

on:
  pull_request:
    # branches-ignore:
    #   - "*"
    paths:
      - "**"
      - "!.github/workflows/*"
      - ".github/workflows/test.yml"
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python_version: ["3.13"]
        compiler:
          - { name: gcc, version: 13, c: gcc-13, cxx: g++-13, package: g++-13 }

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} / ${{ matrix.compiler.cxx }} / python - ${{ matrix.python_version }}

    timeout-minutes: 60

    defaults:
      run:
        shell: bash -l {0}
        working-directory: . # This is something like /home/runner/work/lue/lue

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        id: py
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install packages
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          $py_interpreter -m pip install \
            pre-commit

      - name: Analyse files
        run: |
          pre-commit install
          pre-commit run --all-files
