name: Windows CI

on: [push]

jobs:
    build:

        strategy:
            matrix:
                os: ["windows-latest"]
                python-version: [2.7, 3.8]

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        steps:

        - name: checkout lue
          uses: actions/checkout@v2

        - uses: goanpeca/setup-miniconda@v1
          with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge
        - shell: bash -l {0}
          run: |
              conda install conan docopt ninja numpy psutil sphinx

        - name: configure lue
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build \
                  -G"Ninja" \
                  -DCMAKE_BUILD_TYPE=Release

        - name: build lue
          shell: bash
          run: |
              cmake --build build --target all
