name: Windows CI

on: [push]

jobs:
    build:

        strategy:
            matrix:
                os: ["windows-latest"]
                python-version: [2.7, 3.8]

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        steps:

        - name: checkout lue
          uses: actions/checkout@v2
