name: Windows Conda package

on:
  push:
    branches-ignore:
      - "ghxyz"
    paths:
      - "conanfile.py"
      - ".github/workflows/windows-conda.yml"
      - "source/**"
      - "!source/qa/python/qa/**"
      - "environment/cmake/**"
      - "environment/conda/bld.bat"
      - "environment/conda/conda_build_config.yaml"
      - "environment/conda/meta.yaml"
      - "environment/conda/run_test.py"
      - "environment/script/write_conan_profile.py"

jobs:
    build:

        strategy:
            matrix:
                os: ["windows-2019"]
                python-version: ["3.9"]
            fail-fast: true

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} / python - ${{ matrix.python-version }} / conda

        timeout-minutes: 120

        steps:

        - name: checkout LUE
          uses: actions/checkout@v3

        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge

        - name: Build
          shell: bash -l {0}
          run: |
              conda install boa
              conda mambabuild environment/conda --override-channels --channel conda-forge

        - name: upload
          # TODO if: github.ref == 'refs/heads/master'
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              port: ${{ secrets.FTP_PORT }}
              local-dir: C:/Miniconda/envs/test/conda-bld/win-64/
              server-dir: ${{ secrets.FTP_REMOTE_DIR }}/download/win-64/
